server:
  port: 8081
spring:
  profiles:
    active: local
  application:
    name: titan-shop-boot

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: '*'
    health:
      show-details: always
  metrics:
    tags:
      application: titan-shop-boot

logging:
  path: /apps/logs/springboot/titan-shop-boot
  level:
     org.springframework: INFO
     org.hibernate: INFO
     com.example.springboot.titan.shop.client: DEBUG

user:
  getUserUrl: http://localhost:8080/findByUserId/


info:
  app:
    name: @project.artifactId@
    java:
      source: @java.version@

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

feign:
  client:
    config:
      titan-user-boot:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
  hystrix:
    enabled: true

---
spring:
  profiles: local
